apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kepod-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kepod
roleRef:
  kind: ClusterRole
  name: kepod-cluster-role
  apiGroup: rbac.authorization.k8s.io
