apiVersion: apps/v1
kind: Deployment
metadata:
  name: kepod-api
  namespace: kepod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kepod-api
  template:
    metadata:
      labels:
        app: kepod-api
    spec:
      serviceAccountName: default
      containers:
        - name: kepod-api
          image: 868610198161.dkr.ecr.us-east-1.amazonaws.com/kepod-api:latest
          ports:
            - containerPort: 3000
            - containerPort: 8080
          env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: DYNAMODB_TABLE
              value: "kepod-environments"
            - name: SQS_QUEUE_URL
              value: "https://sqs.us-east-1.amazonaws.com/868610198161/kepod-provisioning-queue"
            - name: S3_BUCKET
              value: "kepod-logs-868610198161"
            - name: API_URL
              value: "http://kepod-api-service.kepod.svc.cluster.local:3000"
          envFrom:
            - secretRef:
                name: kepod-credentials
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"