apiVersion: v1
kind: Secret
metadata:
  name: kepod-credentials
  namespace: kepod
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "<my-access-key-id>"
  AWS_SECRET_ACCESS_KEY: "<my-secret-access-key>"
  AWS_SESSION_TOKEN: "<my-session-token>"