apiVersion: v1
kind: Service
metadata:
  name: kepod-api-service
  namespace: kepod
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/health"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "3000"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "HTTP"
spec:
  selector:
    app: kepod-api
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: websocket
  type: LoadBalancer
  externalTrafficPolicy: Local